apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactions-ui
  labels:
    app: reactions-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reactions-ui
  template:
    metadata:
      labels:
        app: reactions-ui
    spec:
      containers:
        - name: reactions-ui
          image: anurag2911/reactionsui:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: reactions-ui-service
spec:
  selector:
    app: reactions-ui
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
